CREATE TABLE IF NOT EXISTS make_up_class_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    original_course_schedule_id BIGINT NOT NULL,
    original_course_date DATE NOT NULL,
    teacher_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    source_type VARCHAR(50) NOT NULL,
    source_record_id BIGINT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    selected_make_up_start DATETIME(6) NULL,
    selected_make_up_end DATETIME(6) NULL,
    selected_by_teacher_id BIGINT NULL,
    selected_at DATETIME(6) NULL,
    note VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_make_up_source (original_course_schedule_id, teacher_id, source_type, source_record_id),
    KEY idx_make_up_teacher_status (teacher_id, status),
    KEY idx_make_up_original_course (original_course_schedule_id),
    KEY idx_make_up_class_status (class_id, status),
    CONSTRAINT fk_make_up_original_schedule FOREIGN KEY (original_course_schedule_id) REFERENCES class_schedules (id),
    CONSTRAINT fk_make_up_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id),
    CONSTRAINT fk_make_up_class FOREIGN KEY (class_id) REFERENCES classes (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
